# Generated by Django 2.0.3 on 2019-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thebricks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_color', models.CharField(choices=[('black', 'black'), ('brick yellow', 'brick yellow'), ('bright blue', 'bright blue'), ('bright green', 'bright green'), ('bright orange', 'bright orange'), ('bright purple', 'bright purple'), ('bright red', 'bright red'), ('bright reddish violet', 'bright reddish violet'), ('cool yellow', 'cool yellow'), ('dark azure', 'dark azure'), ('dark green', 'dark green'), ('dark orange', 'dark orange'), ('dark stone grey', 'dark stone grey'), ('earth blue', 'earth blue'), ('earth green', 'earth green'), ('flame yellowish green', 'flame yellowish green'), ('light nougat', 'light nougat'), ('light purple', 'light purple'), ('medium azure', 'medium azure'), ('medium lavender', 'medium lavender'), ('medium lilac', 'medium lilac'), ('medium nougat', 'medium nougat'), ('medium stone grey', 'medium stone grey'), ('new dark red', 'new dark red'), ('pink', 'pink'), ('reddish brown', 'reddish brown'), ('sand blue', 'sand blue'), ('sand yellow', 'sand yellow'), ('silver ink', 'silver ink'), ('silver metallic', 'silver metallic'), ('spring yellowish green', 'spring yellowish green'), ('titanium metallic', 'titanium metallic'), ('transparent', 'transparent'), ('transparent blue', 'transparent blue'), ('transparent bright green', 'transparent bright green'), ('transparent bright orange', 'transparent bright orange'), ('transparent green', 'transparent green'), ('transparent light blue', 'transparent light blue'), ('transparent medium reddish violet', 'transparent medium reddish violet'), ('transparent red', 'transparent red'), ('transparent yellow', 'transparent yellow'), ('warm gold', 'warm gold'), ('white', 'white')], default='black', max_length=40)),
                ('brick_type', models.CharField(max_length=40)),
                ('brick_size', models.CharField(max_length=20)),
            ],
        ),
    ]
