# Generated by Django 2.0.3 on 2019-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thebricks',
            name='brick_size',
        ),
        migrations.AddField(
            model_name='thebricks',
            name='brick_height',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='thebricks',
            name='brick_length',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='thebricks',
            name='brick_width',
            field=models.IntegerField(default=1),
        ),
    ]
